# Generated by Django 4.2.29 on 2026-04-16 16:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0004_useraccount_personprofile_guestprofile_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("preferred_language", models.CharField(default="en", max_length=20)),
                ("preferred_script", models.CharField(blank=True, max_length=30)),
                ("timezone", models.CharField(default="UTC", max_length=50)),
                ("preferred_city", models.CharField(blank=True, max_length=120)),
                ("favorite_categories", models.JSONField(blank=True, default=list)),
                ("favorite_deities", models.JSONField(blank=True, default=list)),
                ("interest_tags", models.JSONField(blank=True, default=list)),
                (
                    "astrology_personalization_enabled",
                    models.BooleanField(default=True),
                ),
                ("quiz_public_profile_enabled", models.BooleanField(default=True)),
                ("recommendation_profile", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReadingProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("book", "Book"),
                            ("audio", "Audio"),
                            ("article", "Article"),
                            ("scripture", "Scripture"),
                            ("chant_course", "Chant Course"),
                        ],
                        max_length=40,
                    ),
                ),
                ("object_id", models.CharField(max_length=120)),
                ("progress_percent", models.FloatField(default=0)),
                (
                    "progress_seconds",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "last_position_reference",
                    models.CharField(blank=True, max_length=120),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("last_opened_at", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "guest_profile",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reading_progress",
                        to="accounts.guestprofile",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reading_progress",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-last_opened_at"],
            },
        ),
        migrations.CreateModel(
            name="DailyPersonalizationSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("snapshot_date", models.DateField()),
                ("summary_payload", models.JSONField(blank=True, default=dict)),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "guest_profile",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_snapshots",
                        to="accounts.guestprofile",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_snapshots",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-snapshot_date", "-generated_at"],
            },
        ),
        migrations.CreateModel(
            name="ContentInteraction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("library_book", "Library Book"),
                            ("library_audio", "Library Audio"),
                            ("mantra", "Mantra"),
                            ("article", "Article"),
                            ("quiz", "Quiz"),
                            ("baby_name", "Baby Name"),
                            ("panchaang_day", "Panchaang Day"),
                            ("kundali_report", "Kundali Report"),
                            ("horoscope_report", "Horoscope Report"),
                            ("other", "Other"),
                        ],
                        max_length=40,
                    ),
                ),
                ("object_id", models.CharField(max_length=120)),
                (
                    "interaction_type",
                    models.CharField(
                        choices=[
                            ("viewed", "Viewed"),
                            ("clicked", "Clicked"),
                            ("liked", "Liked"),
                            ("bookmarked", "Bookmarked"),
                            ("started", "Started"),
                            ("resumed", "Resumed"),
                            ("completed", "Completed"),
                            ("shared", "Shared"),
                            ("searched", "Searched"),
                            ("rated", "Rated"),
                            ("downloaded", "Downloaded"),
                        ],
                        max_length=20,
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("occurred_at", models.DateTimeField(auto_now_add=True)),
                (
                    "guest_profile",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="content_interactions",
                        to="accounts.guestprofile",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="content_interactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-occurred_at"],
            },
        ),
        migrations.CreateModel(
            name="Bookmark",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("library_book", "Library Book"),
                            ("library_audio", "Library Audio"),
                            ("mantra", "Mantra"),
                            ("article", "Article"),
                            ("quiz", "Quiz"),
                            ("baby_name", "Baby Name"),
                            ("panchaang_day", "Panchaang Day"),
                            ("kundali_report", "Kundali Report"),
                            ("horoscope_report", "Horoscope Report"),
                            ("other", "Other"),
                        ],
                        max_length=40,
                    ),
                ),
                ("object_id", models.CharField(max_length=120)),
                ("source_context", models.CharField(blank=True, max_length=120)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "guest_profile",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookmarks",
                        to="accounts.guestprofile",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookmarks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RecommendationCache",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "recommendation_type",
                    models.CharField(
                        choices=[
                            ("home_feed", "Home Feed"),
                            ("library", "Library"),
                            ("mantra", "Mantra"),
                            ("quiz", "Quiz"),
                            ("baby_names", "Baby Names"),
                            ("astrology", "Astrology"),
                        ],
                        max_length=40,
                    ),
                ),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("model_version", models.CharField(default="rules-v1", max_length=32)),
                ("source_reasoning", models.JSONField(blank=True, default=dict)),
                (
                    "guest_profile",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendation_caches",
                        to="accounts.guestprofile",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendation_caches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-generated_at"],
                "indexes": [
                    models.Index(
                        fields=["recommendation_type", "expires_at"],
                        name="personaliza_recomme_704198_idx",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="recommendationcache",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("user__isnull", False),
                    ("guest_profile__isnull", False),
                    _connector="OR",
                ),
                name="recommendation_cache_actor_required",
            ),
        ),
        migrations.AddConstraint(
            model_name="readingprogress",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("user__isnull", False),
                    ("guest_profile__isnull", False),
                    _connector="OR",
                ),
                name="progress_actor_required",
            ),
        ),
        migrations.AddConstraint(
            model_name="readingprogress",
            constraint=models.UniqueConstraint(
                condition=models.Q(("user__isnull", False)),
                fields=("user", "content_type", "object_id"),
                name="unique_user_progress",
            ),
        ),
        migrations.AddConstraint(
            model_name="readingprogress",
            constraint=models.UniqueConstraint(
                condition=models.Q(("guest_profile__isnull", False)),
                fields=("guest_profile", "content_type", "object_id"),
                name="unique_guest_progress",
            ),
        ),
        migrations.AddConstraint(
            model_name="dailypersonalizationsnapshot",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("user__isnull", False),
                    ("guest_profile__isnull", False),
                    _connector="OR",
                ),
                name="daily_snapshot_actor_required",
            ),
        ),
        migrations.AddIndex(
            model_name="contentinteraction",
            index=models.Index(
                fields=["content_type", "object_id", "interaction_type"],
                name="personaliza_content_daff0a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="contentinteraction",
            index=models.Index(
                fields=["occurred_at"], name="personaliza_occurre_6aac37_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="contentinteraction",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("user__isnull", False),
                    ("guest_profile__isnull", False),
                    _connector="OR",
                ),
                name="interaction_actor_required",
            ),
        ),
        migrations.AddIndex(
            model_name="bookmark",
            index=models.Index(
                fields=["content_type", "object_id"],
                name="personaliza_content_774568_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="bookmark",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("user__isnull", False),
                    ("guest_profile__isnull", False),
                    _connector="OR",
                ),
                name="bookmark_actor_required",
            ),
        ),
        migrations.AddConstraint(
            model_name="bookmark",
            constraint=models.UniqueConstraint(
                condition=models.Q(("user__isnull", False)),
                fields=("user", "content_type", "object_id"),
                name="unique_user_bookmark",
            ),
        ),
        migrations.AddConstraint(
            model_name="bookmark",
            constraint=models.UniqueConstraint(
                condition=models.Q(("guest_profile__isnull", False)),
                fields=("guest_profile", "content_type", "object_id"),
                name="unique_guest_bookmark",
            ),
        ),
    ]
