# Generated by Django 4.2.29 on 2026-04-19 08:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("accounts", "0005_backfill_user_accounts"),
        ("personalization", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReviewFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_display", models.CharField(blank=True, max_length=120)),
                ("email", models.EmailField(blank=True, max_length=254)),
                (
                    "feature_type",
                    models.CharField(
                        choices=[
                            ("overall", "Overall"),
                            ("ui", "UI"),
                            ("panchaang", "Panchaang"),
                            ("kundali", "Kundali"),
                            ("horoscope", "Horoscope"),
                            ("library", "Library"),
                            ("audio", "Audio"),
                            ("quizzes", "Quizzes"),
                            ("baby_names", "Baby Names"),
                            ("personalization", "Personalization"),
                            ("performance", "Performance"),
                            ("suggestions", "Suggestions"),
                        ],
                        default="overall",
                        max_length=32,
                    ),
                ),
                ("page_url", models.CharField(blank=True, max_length=255)),
                ("rating_overall", models.PositiveSmallIntegerField()),
                ("rating_ui", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "rating_content",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "rating_speed",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("title", models.CharField(blank=True, max_length=160)),
                ("review_text", models.TextField()),
                ("improvement_suggestion", models.TextField(blank=True)),
                (
                    "sentiment",
                    models.CharField(
                        choices=[
                            ("loved", "Loved"),
                            ("good", "Good"),
                            ("needs_improvement", "Needs improvement"),
                        ],
                        default="good",
                        max_length=24,
                    ),
                ),
                ("is_public", models.BooleanField(default=False)),
                ("is_featured", models.BooleanField(default=False)),
                (
                    "moderation_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=24,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "guest_profile",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review_feedback",
                        to="accounts.guestprofile",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review_feedback",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["feature_type", "created_at"],
                        name="personaliza_feature_cd41cb_idx",
                    ),
                    models.Index(
                        fields=["moderation_status", "is_public", "is_featured"],
                        name="personaliza_moderat_7ec0bf_idx",
                    ),
                    models.Index(
                        fields=["rating_overall"], name="personaliza_rating__f79178_idx"
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="reviewfeedback",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("user__isnull", False),
                    ("guest_profile__isnull", False),
                    _connector="OR",
                ),
                name="review_feedback_actor_required",
            ),
        ),
        migrations.AddConstraint(
            model_name="reviewfeedback",
            constraint=models.CheckConstraint(
                check=models.Q(("rating_overall__gte", 1), ("rating_overall__lte", 5)),
                name="review_feedback_rating_overall_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="reviewfeedback",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("rating_ui__isnull", True),
                    models.Q(("rating_ui__gte", 1), ("rating_ui__lte", 5)),
                    _connector="OR",
                ),
                name="review_feedback_rating_ui_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="reviewfeedback",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("rating_content__isnull", True),
                    models.Q(("rating_content__gte", 1), ("rating_content__lte", 5)),
                    _connector="OR",
                ),
                name="review_feedback_rating_content_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="reviewfeedback",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("rating_speed__isnull", True),
                    models.Q(("rating_speed__gte", 1), ("rating_speed__lte", 5)),
                    _connector="OR",
                ),
                name="review_feedback_rating_speed_range",
            ),
        ),
    ]
