# Generated by Django 4.2.29 on 2026-04-16 16:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0004_useraccount_personprofile_guestprofile_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MantraRecommendationRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("rule_type", models.CharField(max_length=40)),
                ("trigger_config", models.JSONField(blank=True, default=dict)),
                ("recommendation_config", models.JSONField(blank=True, default=dict)),
                ("priority", models.PositiveIntegerField(default=100)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["priority", "name"],
            },
        ),
        migrations.CreateModel(
            name="SavedPanchaangPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("city_name", models.CharField(max_length=120)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("preferred_sections", models.JSONField(blank=True, default=list)),
                ("notification_settings", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "guest_profile",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="panchaang_preferences",
                        to="accounts.guestprofile",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="panchaang_preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SavedKundali",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=140)),
                ("source_type", models.CharField(default="generated", max_length=20)),
                ("chart_payload", models.JSONField(blank=True, default=dict)),
                ("summary_payload", models.JSONField(blank=True, default=dict)),
                ("recommendation_payload", models.JSONField(blank=True, default=dict)),
                ("consent_confirmed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "person_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_kundalis",
                        to="accounts.personprofile",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_kundalis",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SavedHoroscopePreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "horoscope_type",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "sign_type",
                    models.CharField(
                        choices=[
                            ("sun", "Sun"),
                            ("moon", "Moon"),
                            ("lagna", "Lagna"),
                            ("chart_based", "Chart Based"),
                        ],
                        default="chart_based",
                        max_length=20,
                    ),
                ),
                ("preferred_language", models.CharField(default="en", max_length=20)),
                ("notification_enabled", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "person_profile",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="horoscope_preferences",
                        to="accounts.personprofile",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="horoscope_preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="savedpanchaangpreference",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("user__isnull", False),
                    ("guest_profile__isnull", False),
                    _connector="OR",
                ),
                name="panchaang_preference_actor_required",
            ),
        ),
        migrations.AddConstraint(
            model_name="savedpanchaangpreference",
            constraint=models.UniqueConstraint(
                condition=models.Q(("user__isnull", False)),
                fields=("user",),
                name="unique_user_panchaang_preference",
            ),
        ),
        migrations.AddConstraint(
            model_name="savedpanchaangpreference",
            constraint=models.UniqueConstraint(
                condition=models.Q(("guest_profile__isnull", False)),
                fields=("guest_profile",),
                name="unique_guest_panchaang_preference",
            ),
        ),
    ]
