# Generated by Django 4.2.29 on 2026-04-16 15:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("accounts", "0002_category_userstats_quizattempt"),
    ]

    operations = [
        migrations.AddField(
            model_name="quizattempt",
            name="accuracy",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="quizattempt",
            name="answer_payload",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="quizattempt",
            name="selected_question_ids",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="quizattempt",
            name="session_token",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=64
            ),
        ),
        migrations.CreateModel(
            name="QuizQuestionMemory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_id", models.CharField(max_length=120)),
                ("seen_count", models.PositiveIntegerField(default=0)),
                ("correct_count", models.PositiveIntegerField(default=0)),
                ("incorrect_count", models.PositiveIntegerField(default=0)),
                ("last_result_correct", models.BooleanField(default=False)),
                ("last_seen_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="question_memory",
                        to="accounts.category",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quiz_question_memory",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-last_seen_at"],
                "unique_together": {("user", "category", "question_id")},
            },
        ),
    ]
