# Generated by Django 4.2.29 on 2026-04-16 16:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("accounts", "0003_quizattempt_accuracy_quizattempt_answer_payload_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(blank=True, max_length=255)),
                ("avatar", models.URLField(blank=True)),
                ("preferred_language", models.CharField(default="en", max_length=20)),
                ("onboarding_completed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="account_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["user__username"],
            },
        ),
        migrations.CreateModel(
            name="PersonProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "profile_type",
                    models.CharField(
                        choices=[
                            ("self", "Self"),
                            ("spouse", "Spouse"),
                            ("child", "Child"),
                            ("parent", "Parent"),
                            ("other", "Other"),
                        ],
                        default="self",
                        max_length=20,
                    ),
                ),
                ("display_name", models.CharField(max_length=120)),
                ("relationship_label", models.CharField(blank=True, max_length=120)),
                ("birth_date", models.DateField()),
                ("birth_time", models.TimeField(blank=True, null=True)),
                ("birth_place_name", models.CharField(max_length=160)),
                ("birth_lat", models.FloatField(blank=True, null=True)),
                ("birth_lng", models.FloatField(blank=True, null=True)),
                ("gender", models.CharField(blank=True, max_length=20)),
                ("notes", models.TextField(blank=True)),
                ("is_primary", models.BooleanField(default=False)),
                ("is_archived", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="person_profiles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-is_primary", "display_name"],
            },
        ),
        migrations.CreateModel(
            name="GuestProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("guest_uuid", models.UUIDField(db_index=True, unique=True)),
                ("session_key", models.CharField(blank=True, max_length=80, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_seen_at", models.DateTimeField(auto_now=True)),
                ("last_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, null=True)),
                ("preferred_language", models.CharField(default="en", max_length=20)),
                (
                    "preferred_location_name",
                    models.CharField(blank=True, max_length=120),
                ),
                ("preferred_location_lat", models.FloatField(blank=True, null=True)),
                ("preferred_location_lng", models.FloatField(blank=True, null=True)),
                ("consent_personalization", models.BooleanField(default=True)),
                ("consent_astrology_storage", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "merged_into_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="merged_guest_profiles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-last_seen_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="personprofile",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_primary", True), ("profile_type", "self")),
                fields=("user",),
                name="accounts_single_primary_self_profile",
            ),
        ),
    ]
