# Generated by Django 4.2.29 on 2026-05-08 15:32

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Pandit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=160)),
                ("slug", models.SlugField(blank=True, max_length=180, unique=True)),
                ("photo", models.URLField(blank=True)),
                ("city", models.CharField(max_length=120)),
                ("area", models.CharField(blank=True, max_length=120)),
                ("languages", models.JSONField(blank=True, default=list)),
                ("experience", models.PositiveIntegerField(default=0)),
                (
                    "rating",
                    models.FloatField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("total_bookings", models.PositiveIntegerField(default=0)),
                ("specialization", models.CharField(max_length=220)),
                ("specialization_tags", models.JSONField(blank=True, default=list)),
                ("bio", models.TextField(blank=True)),
                ("certifications", models.JSONField(blank=True, default=list)),
                ("photos_videos", models.JSONField(blank=True, default=list)),
                ("verified", models.BooleanField(default=True)),
                ("astro_focus", models.JSONField(blank=True, default=list)),
                ("trust_note", models.CharField(blank=True, max_length=180)),
                ("available_today", models.BooleanField(default=False)),
                ("priority_score", models.FloatField(default=0)),
                ("starting_price", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pandit_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-verified", "-rating", "-priority_score", "name"],
            },
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=140, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=160, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("griha_pravesh", "Griha Pravesh"),
                            ("marriage", "Marriage"),
                            ("satyanarayan", "Satyanarayan Puja"),
                            ("rudrabhishek", "Rudrabhishek"),
                            ("naming_ceremony", "Naming Ceremony"),
                            ("havan", "Havan"),
                            ("remedial", "Astro Remedial Puja"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=40,
                    ),
                ),
                ("base_price", models.PositiveIntegerField(default=0)),
                ("duration_minutes", models.PositiveIntegerField(default=90)),
                ("is_featured", models.BooleanField(default=False)),
                ("icon", models.CharField(blank=True, max_length=32)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="PanditService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.PositiveIntegerField()),
                ("is_featured", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("delivery_mode", models.CharField(default="at_home", max_length=40)),
                ("notes", models.TextField(blank=True)),
                (
                    "pandit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pandit_services",
                        to="pandit.pandit",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pandit_links",
                        to="pandit.service",
                    ),
                ),
            ],
            options={
                "ordering": ["price", "service__name"],
                "unique_together": {("pandit", "service")},
            },
        ),
        migrations.CreateModel(
            name="PanditAvailabilitySlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("is_available", models.BooleanField(default=True)),
                ("capacity", models.PositiveIntegerField(default=1)),
                (
                    "pandit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="availability_slots",
                        to="pandit.pandit",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="availability_slots",
                        to="pandit.service",
                    ),
                ),
            ],
            options={
                "ordering": ["date", "start_time"],
                "unique_together": {("pandit", "date", "start_time", "end_time")},
            },
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("time", models.TimeField()),
                ("address", models.TextField()),
                ("city", models.CharField(blank=True, max_length=120)),
                ("notes", models.TextField(blank=True)),
                ("contact_phone", models.CharField(blank=True, max_length=40)),
                ("preferred_language", models.CharField(blank=True, max_length=40)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                            ("cancelled", "Cancelled"),
                            ("completed", "Completed"),
                            ("reschedule_requested", "Reschedule Requested"),
                        ],
                        default="pending",
                        max_length=24,
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("initiated", "Initiated"),
                            ("paid", "Paid"),
                            ("failed", "Failed"),
                            ("refunded", "Refunded"),
                        ],
                        default="pending",
                        max_length=24,
                    ),
                ),
                ("price_amount", models.PositiveIntegerField(default=0)),
                ("payment_note", models.CharField(blank=True, max_length=160)),
                ("confirmation_code", models.CharField(blank=True, max_length=24)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "pandit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookings",
                        to="pandit.pandit",
                    ),
                ),
                (
                    "pandit_service",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bookings",
                        to="pandit.panditservice",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookings",
                        to="pandit.service",
                    ),
                ),
                (
                    "slot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bookings",
                        to="pandit.panditavailabilityslot",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pandit_bookings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "-time", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ]
                    ),
                ),
                ("comment", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "pandit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="pandit.pandit",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pandit_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("user", "pandit")},
            },
        ),
        migrations.AddIndex(
            model_name="pandit",
            index=models.Index(
                fields=["city", "is_active"], name="pandit_pand_city_264ba0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pandit",
            index=models.Index(
                fields=["available_today", "is_active"],
                name="pandit_pand_availab_5a2773_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["user", "status"], name="pandit_book_user_id_0a0883_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["pandit", "status"], name="pandit_book_pandit__893b9b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["date", "time"], name="pandit_book_date_7f252a_idx"
            ),
        ),
    ]
