from django.urls import path

from astrology_consultation.views import (
    AstrologerDashboardAvailabilityApiView,
    AstrologerDashboardProfileApiView,
    AstrologerDashboardSessionsApiView,
    AstrologerDetailApiView,
    AstrologerFiltersApiView,
    AstrologerListApiView,
    ChatMessagesApiView,
    ConsultationHistoryApiView,
    EndChatSessionApiView,
    FavoriteAstrologerApiView,
    ReviewCreateApiView,
    StartChatSessionApiView,
    WalletApiView,
    WalletRechargeApiView,
    astrologer_dashboard_page,
    astrologer_marketplace_page,
    astrologer_profile_page,
    chat_session_page,
    wallet_page,
)

urlpatterns = [
    path('astrologers/', astrologer_marketplace_page, name='astrologers_marketplace'),
    path('astrologers/chat/<uuid:session_id>/', chat_session_page, name='astrologer_chat_session'),
    path('astrologers/<slug:slug>/', astrologer_profile_page, name='astrologer_profile'),
    path('wallet/', wallet_page, name='wallet_page'),
    path('astrologer-dashboard/', astrologer_dashboard_page, name='astrologer_dashboard'),
    path('api/astrologers/', AstrologerListApiView.as_view(), name='api_astrologers'),
    path('api/astrologers/filters/', AstrologerFiltersApiView.as_view(), name='api_astrologer_filters'),
    path('api/astrologers/<slug:slug>/', AstrologerDetailApiView.as_view(), name='api_astrologer_detail'),
    path('api/astrologers/<slug:slug>/favorite/', FavoriteAstrologerApiView.as_view(), name='api_astrologer_favorite'),
    path('api/chat-sessions/start/', StartChatSessionApiView.as_view(), name='api_start_chat_session'),
    path('api/chat-sessions/<uuid:session_id>/messages/', ChatMessagesApiView.as_view(), name='api_chat_messages'),
    path('api/chat-sessions/<uuid:session_id>/end/', EndChatSessionApiView.as_view(), name='api_end_chat_session'),
    path('api/wallet/', WalletApiView.as_view(), name='api_wallet'),
    path('api/wallet/recharge/', WalletRechargeApiView.as_view(), name='api_wallet_recharge'),
    path('api/user/consultations/', ConsultationHistoryApiView.as_view(), name='api_consultation_history'),
    path('api/reviews/', ReviewCreateApiView.as_view(), name='api_astrologer_reviews'),
    path('api/astrologer-dashboard/profile/', AstrologerDashboardProfileApiView.as_view(), name='api_astrologer_dashboard_profile'),
    path('api/astrologer-dashboard/availability/', AstrologerDashboardAvailabilityApiView.as_view(), name='api_astrologer_dashboard_availability'),
    path('api/astrologer-dashboard/sessions/', AstrologerDashboardSessionsApiView.as_view(), name='api_astrologer_dashboard_sessions'),
]
