# Generated by Django 4.2.29 on 2026-05-08 18:40

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0005_backfill_user_accounts"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AstrologerProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("display_name", models.CharField(max_length=140)),
                ("slug", models.SlugField(blank=True, max_length=170, unique=True)),
                ("photo", models.URLField(blank=True)),
                ("bio", models.TextField(blank=True)),
                ("expertise", models.JSONField(blank=True, default=list)),
                ("languages", models.JSONField(blank=True, default=list)),
                ("experience_years", models.PositiveIntegerField(default=1)),
                (
                    "rating",
                    models.FloatField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("total_reviews", models.PositiveIntegerField(default=0)),
                ("total_consultations", models.PositiveIntegerField(default=0)),
                ("price_per_minute", models.PositiveIntegerField(default=25)),
                ("is_verified", models.BooleanField(default=True)),
                ("identity_verified", models.BooleanField(default=True)),
                ("skill_verified", models.BooleanField(default=True)),
                ("is_online", models.BooleanField(default=False)),
                ("available_today", models.BooleanField(default=True)),
                (
                    "response_time",
                    models.PositiveIntegerField(
                        default=2, help_text="Average response time in minutes"
                    ),
                ),
                ("estimated_wait_time", models.PositiveIntegerField(default=1)),
                ("city", models.CharField(blank=True, max_length=120)),
                ("free_first_chat_enabled", models.BooleanField(default=True)),
                ("free_minutes_override", models.PositiveIntegerField(default=5)),
                (
                    "repeat_users_percent",
                    models.PositiveIntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("topic_strengths", models.JSONField(blank=True, default=list)),
                ("consultation_modes", models.JSONField(blank=True, default=list)),
                ("trust_note", models.CharField(blank=True, max_length=180)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="astrologer_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": [
                    "-is_online",
                    "-rating",
                    "-total_consultations",
                    "display_name",
                ],
            },
        ),
        migrations.CreateModel(
            name="ChatSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("requested", "Requested"),
                            ("active", "Active"),
                            ("ended", "Ended"),
                            ("cancelled", "Cancelled"),
                            ("insufficient_balance", "Insufficient balance"),
                        ],
                        default="requested",
                        max_length=32,
                    ),
                ),
                ("question_topic", models.CharField(blank=True, max_length=120)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("rate_per_minute", models.PositiveIntegerField(default=0)),
                ("free_minutes", models.PositiveIntegerField(default=0)),
                ("total_duration_seconds", models.PositiveIntegerField(default=0)),
                (
                    "total_charge",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "birth_profile_shared",
                    models.CharField(
                        choices=[
                            ("none", "Do not share"),
                            ("birth_only", "Birth details only"),
                            ("full_kundali", "Full kundali summary"),
                        ],
                        default="none",
                        max_length=24,
                    ),
                ),
                ("kundali_snapshot", models.JSONField(blank=True, default=dict)),
                ("ai_prechat_summary", models.JSONField(blank=True, default=dict)),
                ("last_user_message_at", models.DateTimeField(blank=True, null=True)),
                ("astrologer_typing", models.BooleanField(default=False)),
                ("low_balance_notified", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "astrologer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_sessions",
                        to="astrology_consultation.astrologerprofile",
                    ),
                ),
                (
                    "person_profile",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="astrology_chat_sessions",
                        to="accounts.personprofile",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="astrology_chat_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WalletTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("credit", "Credit"),
                            ("debit", "Debit"),
                            ("bonus", "Bonus"),
                            ("refund", "Refund"),
                            ("hold", "Hold"),
                        ],
                        max_length=16,
                    ),
                ),
                ("reason", models.CharField(max_length=180)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="wallet_transactions",
                        to="astrology_consultation.chatsession",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wallet_transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Wallet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                ("currency", models.CharField(default="INR", max_length=8)),
                ("first_chat_free_consumed", models.BooleanField(default=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wallet",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sender",
                    models.CharField(
                        choices=[
                            ("user", "User"),
                            ("astrologer", "Astrologer"),
                            ("system", "System"),
                        ],
                        max_length=16,
                    ),
                ),
                ("message", models.TextField()),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("summary", "Summary"),
                            ("system", "System"),
                        ],
                        default="text",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="astrology_consultation.chatsession",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="AstrologerReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ]
                    ),
                ),
                ("comment", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "astrologer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="astrology_consultation.astrologerprofile",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviews",
                        to="astrology_consultation.chatsession",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="astrologer_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AstrologerAvailability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day_of_week",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(6),
                        ]
                    ),
                ),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("is_available", models.BooleanField(default=True)),
                (
                    "astrologer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="availability_windows",
                        to="astrology_consultation.astrologerprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["day_of_week", "start_time"],
            },
        ),
        migrations.CreateModel(
            name="FavoriteAstrologer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "astrologer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorited_by",
                        to="astrology_consultation.astrologerprofile",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorite_astrologers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("user", "astrologer")},
            },
        ),
        migrations.AddIndex(
            model_name="chatsession",
            index=models.Index(
                fields=["user", "status"], name="astrology_c_user_id_50b717_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chatsession",
            index=models.Index(
                fields=["astrologer", "status"], name="astrology_c_astrolo_ea5a38_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="astrologerreview",
            unique_together={("user", "session")},
        ),
        migrations.AddIndex(
            model_name="astrologerprofile",
            index=models.Index(
                fields=["is_online", "is_active"], name="astrology_c_is_onli_24b9df_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="astrologerprofile",
            index=models.Index(
                fields=["city", "is_active"], name="astrology_c_city_ad3737_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="astrologeravailability",
            unique_together={("astrologer", "day_of_week", "start_time", "end_time")},
        ),
    ]
