from datetime import time

from django.contrib.auth.hashers import make_password
from django.db import migrations


def seed_demo_data(apps, schema_editor):
    User = apps.get_model("auth", "User")
    AstrologerProfile = apps.get_model("astrology_consultation", "AstrologerProfile")
    AstrologerAvailability = apps.get_model("astrology_consultation", "AstrologerAvailability")
    AstrologerReview = apps.get_model("astrology_consultation", "AstrologerReview")

    reviewers = []
    for username, first_name in [
        ("consult_reviewer_1", "Aarav"),
        ("consult_reviewer_2", "Meera"),
        ("consult_reviewer_3", "Riya"),
    ]:
        user, _created = User.objects.update_or_create(
            username=username,
            defaults={
                "first_name": first_name,
                "email": f"{username}@example.com",
                "password": make_password(None),
                "is_active": True,
            },
        )
        reviewers.append(user)

    astrologers_payload = [
        {
            "display_name": "Acharya Vedant Rao",
            "slug": "acharya-vedant-rao",
            "photo": "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=900&q=80",
            "bio": "Known for steady Vedic clarity in career, money, and long-cycle transit guidance with a calm conversational style.",
            "expertise": ["vedic_astrology", "career", "finance", "kundali"],
            "languages": ["Hindi", "English"],
            "experience_years": 11,
            "rating": 4.9,
            "total_reviews": 2,
            "total_consultations": 1840,
            "price_per_minute": 45,
            "is_verified": True,
            "identity_verified": True,
            "skill_verified": True,
            "is_online": True,
            "available_today": True,
            "response_time": 2,
            "estimated_wait_time": 1,
            "city": "Bengaluru",
            "free_first_chat_enabled": True,
            "free_minutes_override": 5,
            "repeat_users_percent": 68,
            "topic_strengths": ["career timing", "financial caution", "current dasha"],
            "consultation_modes": ["chat", "call"],
            "trust_note": "Trusted for pragmatic career and money reading backed by chart logic.",
        },
        {
            "display_name": "Astrologer Ira Mukherjee",
            "slug": "astrologer-ira-mukherjee",
            "photo": "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=900&q=80",
            "bio": "Specializes in marriage, emotional compatibility, and family timing with a balanced spiritual and practical tone.",
            "expertise": ["marriage", "love_relationship", "kundali", "muhurat"],
            "languages": ["English", "Hindi", "Bengali"],
            "experience_years": 9,
            "rating": 4.8,
            "total_reviews": 1,
            "total_consultations": 1322,
            "price_per_minute": 39,
            "is_verified": True,
            "identity_verified": True,
            "skill_verified": True,
            "is_online": True,
            "available_today": True,
            "response_time": 3,
            "estimated_wait_time": 2,
            "city": "Kolkata",
            "free_first_chat_enabled": True,
            "free_minutes_override": 5,
            "repeat_users_percent": 61,
            "topic_strengths": ["marriage timing", "compatibility", "family peace"],
            "consultation_modes": ["chat", "call"],
            "trust_note": "Highly rated for calm relationship guidance without fear-driven advice.",
        },
        {
            "display_name": "Pandit Omkar Shastri",
            "slug": "pandit-omkar-shastri",
            "photo": "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=900&q=80",
            "bio": "Focused on muhurat, rituals, and prashna sessions for families planning major events and sacred milestones.",
            "expertise": ["muhurat", "prashna", "vastu"],
            "languages": ["Hindi", "Marathi", "English"],
            "experience_years": 15,
            "rating": 4.7,
            "total_reviews": 1,
            "total_consultations": 980,
            "price_per_minute": 36,
            "is_verified": True,
            "identity_verified": True,
            "skill_verified": True,
            "is_online": False,
            "available_today": True,
            "response_time": 4,
            "estimated_wait_time": 12,
            "city": "Pune",
            "free_first_chat_enabled": True,
            "free_minutes_override": 3,
            "repeat_users_percent": 53,
            "topic_strengths": ["griha pravesh muhurat", "auspicious timing", "prashna"],
            "consultation_modes": ["chat"],
            "trust_note": "Preferred for timing-sensitive rituals and precise muhurat guidance.",
        },
        {
            "display_name": "Tarot Guide Saanvi",
            "slug": "tarot-guide-saanvi",
            "photo": "https://images.unsplash.com/photo-1488426862026-3ee34a7d66df?auto=format&fit=crop&w=900&q=80",
            "bio": "Combines tarot, intuitive reading, and numerology for quick emotional clarity and decision support.",
            "expertise": ["tarot", "numerology", "love_relationship"],
            "languages": ["English", "Hindi", "Gujarati"],
            "experience_years": 6,
            "rating": 4.8,
            "total_reviews": 1,
            "total_consultations": 1545,
            "price_per_minute": 32,
            "is_verified": True,
            "identity_verified": True,
            "skill_verified": True,
            "is_online": True,
            "available_today": True,
            "response_time": 1,
            "estimated_wait_time": 1,
            "city": "Ahmedabad",
            "free_first_chat_enabled": True,
            "free_minutes_override": 5,
            "repeat_users_percent": 59,
            "topic_strengths": ["decision clarity", "love questions", "repeat patterns"],
            "consultation_modes": ["chat"],
            "trust_note": "Fast-response tarot sessions for seekers who want immediate emotional clarity.",
        },
        {
            "display_name": "Drishti Vastu Expert",
            "slug": "drishti-vastu-expert",
            "photo": "https://images.unsplash.com/photo-1504593811423-6dd665756598?auto=format&fit=crop&w=900&q=80",
            "bio": "Vastu consultant for homes, offices, and layout-related energy flow concerns with chart-linked remedies.",
            "expertise": ["vastu", "finance", "career"],
            "languages": ["Hindi", "English"],
            "experience_years": 13,
            "rating": 4.6,
            "total_reviews": 0,
            "total_consultations": 720,
            "price_per_minute": 55,
            "is_verified": True,
            "identity_verified": True,
            "skill_verified": True,
            "is_online": False,
            "available_today": True,
            "response_time": 5,
            "estimated_wait_time": 20,
            "city": "Delhi",
            "free_first_chat_enabled": False,
            "free_minutes_override": 0,
            "repeat_users_percent": 51,
            "topic_strengths": ["home vastu", "office energy", "money flow"],
            "consultation_modes": ["chat", "call"],
            "trust_note": "Strong match for home, office, and property energy consultations.",
        },
        {
            "display_name": "Jyotish Nandini Iyer",
            "slug": "jyotish-nandini-iyer",
            "photo": "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?auto=format&fit=crop&w=900&q=80",
            "bio": "Reads dasha, transit, and emotional cycles with strong focus on health, stress patterns, and timing windows.",
            "expertise": ["vedic_astrology", "health", "kundali"],
            "languages": ["Tamil", "English", "Hindi"],
            "experience_years": 8,
            "rating": 4.7,
            "total_reviews": 0,
            "total_consultations": 908,
            "price_per_minute": 34,
            "is_verified": True,
            "identity_verified": True,
            "skill_verified": True,
            "is_online": True,
            "available_today": True,
            "response_time": 2,
            "estimated_wait_time": 3,
            "city": "Chennai",
            "free_first_chat_enabled": True,
            "free_minutes_override": 5,
            "repeat_users_percent": 57,
            "topic_strengths": ["stress cycles", "healing timing", "planetary pressure"],
            "consultation_modes": ["chat", "call"],
            "trust_note": "Thoughtful chart reading with emphasis on health patterns and calm next steps.",
        },
        {
            "display_name": "Acharya Ritam Banerjee",
            "slug": "acharya-ritam-banerjee",
            "photo": "https://images.unsplash.com/photo-1504257432389-52343af06ae3?auto=format&fit=crop&w=900&q=80",
            "bio": "Combines prashna and Vedic reading for direct answers around blocked situations, delayed outcomes, and decisions.",
            "expertise": ["prashna", "vedic_astrology", "career"],
            "languages": ["Bengali", "Hindi", "English"],
            "experience_years": 12,
            "rating": 4.8,
            "total_reviews": 0,
            "total_consultations": 1130,
            "price_per_minute": 42,
            "is_verified": True,
            "identity_verified": True,
            "skill_verified": True,
            "is_online": False,
            "available_today": False,
            "response_time": 6,
            "estimated_wait_time": 30,
            "city": "Kolkata",
            "free_first_chat_enabled": True,
            "free_minutes_override": 3,
            "repeat_users_percent": 49,
            "topic_strengths": ["blocked situations", "decision windows", "career reversals"],
            "consultation_modes": ["chat"],
            "trust_note": "Useful for direct question-based readings where timing is critical.",
        },
        {
            "display_name": "Rudra Palmistry Studio",
            "slug": "rudra-palmistry-studio",
            "photo": "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=900&q=80",
            "bio": "Palmistry-led insight for relationship tendencies, effort patterns, and life-shift periods.",
            "expertise": ["palmistry", "love_relationship", "career"],
            "languages": ["Hindi", "English", "Punjabi"],
            "experience_years": 7,
            "rating": 4.5,
            "total_reviews": 0,
            "total_consultations": 560,
            "price_per_minute": 29,
            "is_verified": True,
            "identity_verified": True,
            "skill_verified": True,
            "is_online": True,
            "available_today": True,
            "response_time": 2,
            "estimated_wait_time": 2,
            "city": "Chandigarh",
            "free_first_chat_enabled": True,
            "free_minutes_override": 5,
            "repeat_users_percent": 43,
            "topic_strengths": ["habit patterns", "relationships", "effort cycles"],
            "consultation_modes": ["chat"],
            "trust_note": "Accessible guidance for seekers who prefer pattern-based readings.",
        },
        {
            "display_name": "Guru Prerana Joshi",
            "slug": "guru-prerana-joshi",
            "photo": "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=900&q=80",
            "bio": "Offers marriage, fertility, and family stability consultations with chart-backed timing interpretation.",
            "expertise": ["marriage", "love_relationship", "muhurat"],
            "languages": ["Hindi", "Marathi", "Gujarati"],
            "experience_years": 10,
            "rating": 4.9,
            "total_reviews": 0,
            "total_consultations": 1498,
            "price_per_minute": 48,
            "is_verified": True,
            "identity_verified": True,
            "skill_verified": True,
            "is_online": True,
            "available_today": True,
            "response_time": 1,
            "estimated_wait_time": 1,
            "city": "Mumbai",
            "free_first_chat_enabled": False,
            "free_minutes_override": 0,
            "repeat_users_percent": 72,
            "topic_strengths": ["marriage stability", "family planning", "auspicious timing"],
            "consultation_modes": ["chat", "call"],
            "trust_note": "Premium consultation style for family, marriage, and long-term emotional planning.",
        },
        {
            "display_name": "Nakshatra Analyst Kavish",
            "slug": "nakshatra-analyst-kavish",
            "photo": "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=900&q=80",
            "bio": "Deep-dives into moon sign, nakshatra, and behavioral patterns for seekers wanting precise self-understanding.",
            "expertise": ["kundali", "vedic_astrology", "career"],
            "languages": ["Hindi", "English"],
            "experience_years": 5,
            "rating": 4.6,
            "total_reviews": 0,
            "total_consultations": 670,
            "price_per_minute": 27,
            "is_verified": True,
            "identity_verified": True,
            "skill_verified": True,
            "is_online": False,
            "available_today": True,
            "response_time": 4,
            "estimated_wait_time": 14,
            "city": "Jaipur",
            "free_first_chat_enabled": True,
            "free_minutes_override": 5,
            "repeat_users_percent": 46,
            "topic_strengths": ["nakshatra profile", "self pattern", "career fit"],
            "consultation_modes": ["chat"],
            "trust_note": "Strong fit for users who want precise self-analysis from moon and nakshatra layers.",
        },
        {
            "display_name": "Astro Mentor Harini",
            "slug": "astro-mentor-harini",
            "photo": "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=900&q=80",
            "bio": "Guides women and young professionals through career transitions, confidence cycles, and decision timing.",
            "expertise": ["career", "finance", "numerology"],
            "languages": ["English", "Tamil", "Hindi"],
            "experience_years": 4,
            "rating": 4.7,
            "total_reviews": 0,
            "total_consultations": 480,
            "price_per_minute": 24,
            "is_verified": True,
            "identity_verified": True,
            "skill_verified": True,
            "is_online": True,
            "available_today": True,
            "response_time": 2,
            "estimated_wait_time": 2,
            "city": "Hyderabad",
            "free_first_chat_enabled": True,
            "free_minutes_override": 5,
            "repeat_users_percent": 41,
            "topic_strengths": ["job shifts", "money discipline", "confidence cycles"],
            "consultation_modes": ["chat"],
            "trust_note": "Quick-response advisor for young professionals and transition periods.",
        },
        {
            "display_name": "Vastu & Muhurat Guru Dev",
            "slug": "vastu-muhurat-guru-dev",
            "photo": "https://images.unsplash.com/photo-1463453091185-61582044d556?auto=format&fit=crop&w=900&q=80",
            "bio": "Specializes in house moves, launches, and ritual timing using muhurat backed by practical scheduling advice.",
            "expertise": ["vastu", "muhurat", "finance"],
            "languages": ["Hindi", "English", "Kannada"],
            "experience_years": 17,
            "rating": 4.8,
            "total_reviews": 0,
            "total_consultations": 1715,
            "price_per_minute": 58,
            "is_verified": True,
            "identity_verified": True,
            "skill_verified": True,
            "is_online": False,
            "available_today": True,
            "response_time": 5,
            "estimated_wait_time": 18,
            "city": "Bengaluru",
            "free_first_chat_enabled": False,
            "free_minutes_override": 0,
            "repeat_users_percent": 65,
            "topic_strengths": ["property timing", "business launch", "ritual windows"],
            "consultation_modes": ["chat", "call"],
            "trust_note": "Chosen for high-trust home, property, and launch timing decisions.",
        },
    ]

    astrologers = {}
    for payload in astrologers_payload:
        astrologer, _created = AstrologerProfile.objects.update_or_create(
            slug=payload["slug"],
            defaults=payload,
        )
        astrologers[astrologer.slug] = astrologer

    for astrologer in astrologers.values():
        for day, start_hour, end_hour in [(1, 10, 14), (3, 16, 20), (5, 11, 15)]:
            AstrologerAvailability.objects.update_or_create(
                astrologer=astrologer,
                day_of_week=day,
                start_time=time(start_hour, 0),
                end_time=time(end_hour, 0),
                defaults={"is_available": True},
            )

    reviews_payload = [
        ("acharya-vedant-rao", reviewers[0], 5, "Grounded, clear, and very practical about timing."),
        ("acharya-vedant-rao", reviewers[1], 5, "One of the few astrologers who explained finance carefully instead of vaguely."),
        ("astrologer-ira-mukherjee", reviewers[2], 5, "Warm guidance and very helpful for relationship clarity."),
        ("pandit-omkar-shastri", reviewers[0], 4, "Precise muhurat guidance and good ritual clarity."),
        ("tarot-guide-saanvi", reviewers[1], 5, "Quick, direct, and emotionally accurate."),
    ]

    for slug, user, rating, comment in reviews_payload:
        AstrologerReview.objects.update_or_create(
            user=user,
            astrologer=astrologers[slug],
            session=None,
            defaults={"rating": rating, "comment": comment},
        )


def remove_demo_data(apps, schema_editor):
    User = apps.get_model("auth", "User")
    AstrologerAvailability = apps.get_model("astrology_consultation", "AstrologerAvailability")
    AstrologerReview = apps.get_model("astrology_consultation", "AstrologerReview")
    AstrologerProfile = apps.get_model("astrology_consultation", "AstrologerProfile")

    slugs = [
        "acharya-vedant-rao",
        "astrologer-ira-mukherjee",
        "pandit-omkar-shastri",
        "tarot-guide-saanvi",
        "drishti-vastu-expert",
        "jyotish-nandini-iyer",
        "acharya-ritam-banerjee",
        "rudra-palmistry-studio",
        "guru-prerana-joshi",
        "nakshatra-analyst-kavish",
        "astro-mentor-harini",
        "vastu-muhurat-guru-dev",
    ]

    AstrologerAvailability.objects.filter(astrologer__slug__in=slugs).delete()
    AstrologerReview.objects.filter(astrologer__slug__in=slugs).delete()
    AstrologerProfile.objects.filter(slug__in=slugs).delete()
    User.objects.filter(username__in=["consult_reviewer_1", "consult_reviewer_2", "consult_reviewer_3"]).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("astrology_consultation", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(seed_demo_data, remove_demo_data),
    ]
